name: HidePlayersInWorld
version: 1.1
main: io.moonlightnovamc.plugin.palyerhideinworld.Palyerhideinworld
api-version: 1.20
author: SafeZoneMoRi
description: Hide players from each other in specified worlds
commands:
  hideworldreload:
    description: Reload the HidePlayersInWorld config
    permission: hideworld.reload
    usage: /hideworldreload
permissions:
  hideworld.reload:
    description: Allows reloading the plugin config
    default: op
